### ISSUE TITLE
Premature end of Content-Length delimited message body

### ISSUE THREAD

**Issue by platstar** [hailin0/elasticsearch-analysis-dynamic-synonym#2]
我也昰從 bells/elasticsearch-analysis-dynamic-synonym 那來的
遇到的問題挺像的,已经配置好，但是远程请求txt文件报错
elasticsearch 2.4.3

`[2017-03-07 14:01:35,553][INFO ][node                     ] [node.9202.243] started
[2017-03-07 14:01:36,553][INFO ][dynamic-synonym          ] start reload remote synonym from http://192.168.57.15/xxx/synonym/getdata.
[2017-03-07 14:01:36,569][ERROR][dynamic-synonym          ] reload remote synonym http://192.168.57.15/xxx/synonym/getdata error!
org.apache.http.ConnectionClosedException: Premature end of Content-Length delimited message body (expected: 229; received: 0
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:142)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:120)
        at java.util.zip.CheckedInputStream.read(CheckedInputStream.java:59)
        at java.util.zip.GZIPInputStream.readUByte(GZIPInputStream.java:266)
        at java.util.zip.GZIPInputStream.readUShort(GZIPInputStream.java:258)
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:164)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at org.apache.http.client.protocol.ResponseContentEncoding$1.create(ResponseContentEncoding.java:67)
        at org.apache.http.client.entity.LazyDecompressingInputStream.initWrapper(LazyDecompressingInputStream.java:54)
        at org.apache.http.client.entity.LazyDecompressingInputStream.read(LazyDecompressingInputStream.java:72)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.BufferedReader.fill(BufferedReader.java:161)
        at java.io.BufferedReader.readLine(BufferedReader.java:324)
        at java.io.LineNumberReader.readLine(LineNumberReader.java:201)
        at org.apache.lucene.analysis.synonym.SolrSynonymParser.addInternal(SolrSynonymParser.java:82)
        at org.apache.lucene.analysis.synonym.SolrSynonymParser.parse(SolrSynonymParser.java:70)
        at com.bellszhu.elasticsearch.plugin.synonym.analysis.RemoteSynonymFile.reloadSynonymMap(RemoteSynonymFile.java:75)
        at com.bellszhu.elasticsearch.plugin.synonym.analysis.DynamicSynonymTokenFilterFactory.<init>(DynamicSynonymTokenFilterFactory.java:120)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
`

`
index:
  analysis:
    filter:
      remote_synonym:
          type: dynamic_synonym
          synonyms_path: http://192.168.57.15/xxx/synonym/getdata
          interval: 30
      local_synonym:
          type: dynamic_synonym
          synonyms_path: analysis/synonym.txt
 `
也試過     synonyms_path: http://192.168.57.15/xxx.synonym.txt 
結果一樣報錯

**Comment by hailin0** [comment]
你试过我的吗？  我的现在线上使用稳定呢

**Comment by hailin0** [comment]
可以加qq详细聊一下  568847614

**Comment by platstar** [comment]
原本搞不清谁的版本才是最原始的版本,想说都差不多
依你的建议,实际试过你的版本后果然正常,
bells/elasticsearch-analysis-dynamic-synonym 版本是有问题的
感谢

**Comment by hailin0** [comment]
嗯    基本上改了很多  也测了很久  除了包名没变  其他都变了。。。

**Comment by platstar** [comment]
有微信號嗎？　同义词文件似乎不能支持中英設置和空白字元？

**Comment by hailin0** [comment]
把你的内容贴上来吧

**Comment by platstar** [comment]
有空格的同义词會這樣是正常的嗎, sony ericsson 被拆開了

sony ericsson,索尼愛立信,愛立信
http://localhost:9200/test2/_analyze?analyzer=ik_smart_syno&text=sony%20ericsson
{
tokens: [
{
token: "sony",
start_offset: 0,
end_offset: 4,
type: "ENGLISH",
position: 0
},
{
token: "索尼愛立信",
start_offset: 0,
end_offset: 13,
type: "SYNONYM",
position: 0
},
{
token: "愛立信",
start_offset: 0,
end_offset: 13,
type: "SYNONYM",
position: 0
},
{
token: "ericsson",
start_offset: 5,
end_offset: 13,
type: "ENGLISH",
position: 1
}
]
}

**Comment by platstar** [comment]
i-pod, i pod, i pad, ipod
http://localhost:9200/test/_analyze?analyzer=ik_smart_syno&text=ipod
{
tokens: [
{
token: "ipod",
start_offset: 0,
end_offset: 4,
type: "ENGLISH",
position: 0
},
{
token: "﻿i-pod",
start_offset: 0,
end_offset: 4,
type: "SYNONYM",
position: 0
},
{
token: "i",
start_offset: 0,
end_offset: 4,
type: "SYNONYM",
position: 0
},
{
token: "i",
start_offset: 0,
end_offset: 4,
type: "SYNONYM",
position: 0
},
{
token: "pod",
start_offset: 0,
end_offset: 4,
type: "SYNONYM",
position: 1
},
{
token: "pad",
start_offset: 0,
end_offset: 4,
type: "SYNONYM",
position: 1
}
]
}

**Comment by platstar** [comment]
iphone, i phone
http://localhost:9200/test/_analyze?analyzer=ik_smart_syno&text=iphone
{
tokens: [
{
token: "iphone",
start_offset: 0,
end_offset: 6,
type: "ENGLISH",
position: 0
},
{
token: "i",
start_offset: 0,
end_offset: 6,
type: "SYNONYM",
position: 0
},
{
token: "phone",
start_offset: 0,
end_offset: 6,
type: "SYNONYM",
position: 1
}
]
}

**Comment by hailin0** [comment]
同义词是在词的基础上做的，如果不想拆开，先确保在词库中已经有这个词吧

**Comment by platstar** [comment]
词库已经有这个词了, 英文词库有空格就会有这问题

**Comment by hailin0** [comment]
分词设置删除空格可以满足吗

**Comment by platstar** [comment]
谢谢作者的协助
英文若有空格是IK分词原本就不支持的,英文也不是IK中文分词要处理的
